//LOGIN
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
//USER
export const USER_REQUEST = 'USER_REQUEST';
export const USER_LOAD_SUCCESS = 'USER_LOAD_SUCCESS';
//ACCOUNT//
export const ACCOUNT_FULL_BALANCE_REQUEST = 'ACCOUNT_FULL_BALANCE_REQUEST';
export const ACCOUNT_FULL_BALANCE_SUCCESS = 'ACCOUNT_FULL_BALANCE_SUCCESS';
export const ACCOUNT_SET_CURRENT = 'ACCOUNT_SET_CURRENT';
export const ACCOUNT_CURRENT_SUCCESS = 'ACCOUNT_CURRENT_SUCCESS';
export const ACCOUNT_MIN_REQUEST = 'ACCOUNT_MIN_REQUEST';
export const ACCOUNT_MIN_SUCCESS = 'ACCOUNT_MIN_SUCCESS';
