//LOGIN
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
//USER
export const USER_REQUEST = 'USER_REQUEST';
export const USER_LOAD_SUCCESS = 'USER_LOAD_SUCCESS';
//ACCOUNT//TODO:CREATE REDUCER
export const ACCOUNT_FULL_BALANCE_REQUEST = 'ACCOUNT_FULL_BALANCE_REQUEST';
export const ACCOUNT_FULL_BALANCE_SUCCESS = 'ACCOUNT_FULL_BALANCE_SUCCESS';